// Autogenerated from Pigeon (v26.0.1), do not edit directly.
// See also: https://pub.dev/packages/pigeon

#import <Foundation/Foundation.h>

@protocol FlutterBinaryMessenger;
@protocol FlutterMessageCodec;
@class FlutterError;
@class FlutterStandardTypedData;

NS_ASSUME_NONNULL_BEGIN


/// The codec used by all APIs.
NSObject<FlutterMessageCodec> *SRGetMessagesCodec(void);

@protocol SRSpeechRecognizerSchema
- (void)getSpeechTranscriptLocale:(nullable NSString *)locale completion:(void (^)(NSString *_Nullable, FlutterError *_Nullable))completion;
@end

extern void SetUpSRSpeechRecognizerSchema(id<FlutterBinaryMessenger> binaryMessenger, NSObject<SRSpeechRecognizerSchema> *_Nullable api);

extern void SetUpSRSpeechRecognizerSchemaWithSuffix(id<FlutterBinaryMessenger> binaryMessenger, NSObject<SRSpeechRecognizerSchema> *_Nullable api, NSString *messageChannelSuffix);

NS_ASSUME_NONNULL_END
