// Autogenerated from Pigeon (v26.0.1), do not edit directly.
// See also: https://pub.dev/packages/pigeon

#import "messages.g.h"

#if TARGET_OS_OSX
#import <FlutterMacOS/FlutterMacOS.h>
#else
#import <Flutter/Flutter.h>
#endif

#if !__has_feature(objc_arc)
#error File requires ARC to be enabled.
#endif

static NSArray<id> *wrapResult(id result, FlutterError *error) {
  if (error) {
    return @[
      error.code ?: [NSNull null], error.message ?: [NSNull null], error.details ?: [NSNull null]
    ];
  }
  return @[ result ?: [NSNull null] ];
}

static id GetNullableObjectAtIndex(NSArray<id> *array, NSInteger key) {
  id result = array[key];
  return (result == [NSNull null]) ? nil : result;
}

@interface SRMessagesPigeonCodecReader : FlutterStandardReader
@end
@implementation SRMessagesPigeonCodecReader
- (nullable id)readValueOfType:(UInt8)type {
  switch (type) {
    default:
      return [super readValueOfType:type];
  }
}
@end

@interface SRMessagesPigeonCodecWriter : FlutterStandardWriter
@end
@implementation SRMessagesPigeonCodecWriter
- (void)writeValue:(id)value {
  {
    [super writeValue:value];
  }
}
@end

@interface SRMessagesPigeonCodecReaderWriter : FlutterStandardReaderWriter
@end
@implementation SRMessagesPigeonCodecReaderWriter
- (FlutterStandardWriter *)writerWithData:(NSMutableData *)data {
  return [[SRMessagesPigeonCodecWriter alloc] initWithData:data];
}
- (FlutterStandardReader *)readerWithData:(NSData *)data {
  return [[SRMessagesPigeonCodecReader alloc] initWithData:data];
}
@end

NSObject<FlutterMessageCodec> *SRGetMessagesCodec(void) {
  static FlutterStandardMessageCodec *sSharedObject = nil;
  static dispatch_once_t sPred = 0;
  dispatch_once(&sPred, ^{
    SRMessagesPigeonCodecReaderWriter *readerWriter = [[SRMessagesPigeonCodecReaderWriter alloc] init];
    sSharedObject = [FlutterStandardMessageCodec codecWithReaderWriter:readerWriter];
  });
  return sSharedObject;
}
void SetUpSRSpeechRecognizerSchema(id<FlutterBinaryMessenger> binaryMessenger, NSObject<SRSpeechRecognizerSchema> *api) {
  SetUpSRSpeechRecognizerSchemaWithSuffix(binaryMessenger, api, @"");
}

void SetUpSRSpeechRecognizerSchemaWithSuffix(id<FlutterBinaryMessenger> binaryMessenger, NSObject<SRSpeechRecognizerSchema> *api, NSString *messageChannelSuffix) {
  messageChannelSuffix = messageChannelSuffix.length > 0 ? [NSString stringWithFormat: @".%@", messageChannelSuffix] : @"";
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:[NSString stringWithFormat:@"%@%@", @"dev.flutter.pigeon.speech_recognizer.SpeechRecognizerSchema.getSpeechTranscript", messageChannelSuffix]
        binaryMessenger:binaryMessenger
        codec:SRGetMessagesCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(getSpeechTranscriptLocale:completion:)], @"SRSpeechRecognizerSchema api (%@) doesn't respond to @selector(getSpeechTranscriptLocale:completion:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        NSArray<id> *args = message;
        NSString *arg_locale = GetNullableObjectAtIndex(args, 0);
        [api getSpeechTranscriptLocale:arg_locale completion:^(NSString *_Nullable output, FlutterError *_Nullable error) {
          callback(wrapResult(output, error));
        }];
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
}
